### ISSUE TITLE
[BUG] Crashed on startup

### ISSUE THREAD

**Issue by oof100200** [mariumbacchus/Soulslike-Weaponry#177]
**Minecraft, modloader and mod versions**
Example:
Minecraft: 1.20.1
NeoForge: 47.1.105
Soulslike-Weaponry: 1.1.4.4c

**Describe the bug**
Server just crashed on startup without connector. 

**Add logs**
[A log of the incident, i.e crash log if a crash happened or a log giving other warnings before the issue occured if necessary.](https://gist.github.com/oof100200/07030194decc74d84b00878a91934048)

**Comment by KiraKayn** [comment]
Fixed in the latest version, had the same issue

**Comment by Danmccool** [comment]
its not fixed

**Comment by oof100200** [comment]
> Fixed in the latest version, had the same issue

its not fixed

**Comment by KiraKayn** [comment]
Ah you are already on that version, unsure then, provide a crash report aswell, its easier to read that in my experience

**Comment by oof100200** [comment]
> 啊，你已经在用那个版本了，不确定，也提供一份崩溃报告，根据我的经验，这样更容易阅读。

This issue uses the latest version of the mod. Still crashed.

**Comment by oof100200** [comment]
> Ah you are already on that version, unsure then, provide a crash report aswell, its easier to read that in my experience

thanks for the help, i have downgrade projectile damege mod's version, it works.

**Comment by Ashuntoi** [comment]
Try to downgrade this mod projectile_damage-forge-3.2.3+1.20.1, use this version >projectile_damage-forge-3.2.2+1.20.1 for me this fix the crash.

**Comment by oof100200** [comment]
> 尝试降级此 mod projectile_damage-forge-3.2.3+1.20.1，对我而言使用此版本 >projectile_damage-forge-3.2.2+1.20.1 可修复崩溃问题。

thanks

**Comment by mariumbacchus** [comment]
Yeah seems to be an issue with the latest projectile damage attribute mod version (3.2.3). I've restricted the mod to only accept version 3.2.2 to avoid this issue with the latest patch (1.1.4.4d).
